### PR TITLE
Add Generate support in mining.go.

### PR DESCRIPTION
**Pull request by aakselrod**
- Create FutureGenerateResult type with Receive() method
- Create GenerateAsync method for Client which returns a
  FutureGenerateResult
- Create Generate method for Client which calls GenerateAsync
  and then calls Receive() on the returned FutureGenerateResult

### CODE REVIEW

**Comment by davecgh** [comment]
Thanks.  Reads well so far.  Obviously it also depends on btcsuite/btcd#407.

**Comment by aakselrod** [comment]
Sorry, it wasn't building because I used `int` instead of `uint32` for numBlocks. Still working on this.

**Comment by davecgh** [comment]
I commented on btcsuite/btcd#407 with a few remaining things, but once that is in, I'll trigger a rebuild of Travis and test this one out.

**Comment by davecgh** [comment]
OK

**Pull request merged**
